[development]
dynaconf_merge = true

[development.security]
# openssl rand -hex 32
SECRET_KEY = "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"

[production]
dynaconf_merge = true

[production.security]
SECRET_KEY = "@vault path/to/vault/secret"
