version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/fastapi_project_template
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: fastapi_project_template_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/fastapi_project_template_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=fastapi_project_template, fastapi_project_template_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
